Source/Web/HelpMyBook.Web/Controllers/BooksController.cs
namespace HelpMyBook.Web.Controllers
{
    using System.IO;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Web.Mvc;
    using HelpMyBook.Common;
    using HelpMyBook.Data.Models;
    using HelpMyBook.Services.Data.Contracts;
    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using reCAPTCHA.MVC;
    using ViewModels.Books;
    using ViewModels.UserProfile;

    public class BooksController : BaseController
    {
        private readonly IUserService users;
        private readonly IBookService books;
        private readonly IFilesService files;
        private readonly IDonationsService donations;

        public BooksController(IUserService users, IBookService books, IFilesService files, IDonationsService donations)
        {
            this.users = users;
            this.books = books;
            this.files = files;
            this.donations = donations;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            var user = this.users.GetUser(this.User.Identity.GetUserId());
            if (user.BookId != null)
            {
                this.TempData.Clear();
                this.TempData[GlobalConstants.MessageNameError] = "You've already created a book!";

                return this.Redirect("/");
            }

            return this.View();
        }

        [HttpPost]
        [Authorize]
        [CaptchaValidator(
        PrivateKey = "6LcfKBkTAAAAAHpUhmpjNks48KyW6g9ITJHFUj2i",
        ErrorMessage = "Invalid input captcha.",
        RequiredMessage = "The captcha field is required.")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookCreateModel model, bool downloadable)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.User.Identity.GetUserId();

            var book = new Book
            {
                Title = model.Title,
                Description = model.Description,
                RequredMoney = model.RequredMoney
            };

            if (model.File != null)
            {
                int idx = model.File.FileName.LastIndexOf('.');
                if (idx == -1)
                {
                    this.ModelState.AddModelError(string.Empty, "File must have an extention!");
                    return this.View();
                }

                var fileName = model.File.FileName.Substring(0, idx);
                var fileExtention = model.File.FileName.Substring(idx + 1);

                if (!Regex.IsMatch(fileExtention, ValidationConstants.FileExtentionRegex))
                {
                    this.ModelState.AddModelError(string.Empty, "File extention not supported!");
                    return this.View();
                }

                using (var memory = new MemoryStream())
                {
                    model.File.InputStream.CopyTo(memory);
                    var content = memory.GetBuffer();

                    book.BookFile = new BookFile
                    {
                        Downloadable = downloadable,
                        Content = content,
                        Name = fileName,
                        FileExtension = fileExtention
                    };
                }
            }

            var user = this.users.GetUser(this.User.Identity.GetUserId());

            var creationResult = this.books.Create(book);

            this.users.BindBookAndUser(user.Id, creationResult.Id);

            this.TempData.Clear();

            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly created a book!";

            return this.RedirectToAction("Details", new { id = creationResult.Id });
        }

        [HttpGet]
        public ActionResult Index()
        {
            var books = this.books.GetBooks().To<BookIndexViewModel>().ToList();
            var hasBook = false;
            if (this.User.Identity.IsAuthenticated)
            {
                var user = this.users.GetUser(this.User.Identity.GetUserId());
                if (user.BookId != null)
                {
                    hasBook = true;
                }
            }

            var model = new BookIndexDataModel()
            {
                Books = books,
                HasBook = hasBook
            };

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Downloads()
        {
            var books = this.books.GetDownloadableBooks().To<BookViewModel>().ToList();

            return this.View(books);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var viewmodel = this.books.GetBookDetails(id).To<BookDetailsViewModel>().FirstOrDefault();

            if (this.User.Identity.IsAuthenticated)
            {
                var user = this.users.GetUser(this.User.Identity.GetUserId());
                if (user.BookId == viewmodel.Id)
                {
                    viewmodel.OwnerLooking = true;
                }

                viewmodel.MoneyPartialModel = new UserMoneyModel()
                {
                    UserId = user.Id,
                    BookId = viewmodel.Id,
                    Money = user.Money
                };
            }

            return this.View(viewmodel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var viewmodel = this.books.GetBookDetails(id).To<BookDetailsViewModel>().FirstOrDefault();

            var user = this.users.GetUser(this.User.Identity.GetUserId());
            if (user.BookId != id)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You are not allowed to edit this book!";
                return this.RedirectToAction("Details", new { id = id });
            }

            return this.View(viewmodel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBookInfo(BookDetailsViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("Edit", model);
            }

            var book = this.books.GetBookDetails(model.Id).FirstOrDefault();

            book.Title = model.Title;
            book.Description = model.Description;

            var creationResult = this.books.Update(book);

            this.TempData.Clear();
            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly created a book!";

            return this.RedirectToAction("Details", new { id = creationResult.Id });
        }

        [HttpGet]
        [Authorize]
        public ActionResult FileUpdate(int bookId)
        {
            var fileId = this.books.GetBookDetails(bookId).FirstOrDefault().BookFileId;
            var model = new BookFileUpdateModel
            {
                BookFileId = fileId,
                BookId = bookId
            };
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult FileUpdate(BookFileUpdateModel model)
        {
            if (model.File != null)
            {
                int idx = model.File.FileName.LastIndexOf('.');
                if (idx == -1)
                {
                    this.ModelState.AddModelError(string.Empty, "File must have an extention!");
                    return this.View("FileUpdate", model);
                }

                var fileName = model.File.FileName.Substring(0, idx);
                var fileExtention = model.File.FileName.Substring(idx + 1);

                if (!Regex.IsMatch(fileExtention, ValidationConstants.FileExtentionRegex))
                {
                    this.ModelState.AddModelError(string.Empty, "File extention not supported!");
                    return this.View("FileUpdate", model);
                }

                using (var memory = new MemoryStream())
                {
                    model.File.InputStream.CopyTo(memory);
                    var content = memory.GetBuffer();
                    var book = this.books.GetBookDetails(model.BookId).FirstOrDefault();
                    if (book.BookFileId == null)
                    {
                        book.BookFile = new BookFile
                        {
                            Downloadable = model.Downloadable,
                            Content = content,
                            Name = fileName,
                            FileExtension = fileExtention
                        };
                    }
                    else
                    {
                        book.BookFile.Downloadable = model.Downloadable;
                        book.BookFile.Content = content;
                        book.BookFile.Name = fileName;
                        book.BookFile.FileExtension = fileExtention;
                    }

                    var result = this.books.Update(book);
                }
            }

            return this.RedirectToAction("Details", new { id = model.BookId });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Contribute(UserMoneyModel model)
        {
            if (model.Money < model.Contribution)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You can't contribute more than you have!";
                return this.RedirectToAction("Details", new { id = model.BookId });
            }

            if (model.Contribution == 0)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You can't contribute 0$!";
                return this.RedirectToAction("Details", new { id = model.BookId });
            }

            var user = this.users.GetUser(model.UserId);

            var donation = new Donation()
            {

Source/Web/HelpMyBook.Web/Controllers/InformationController.cs
namespace HelpMyBook.Web.Controllers
{
    using System.Web.Mvc;

    public class InformationController : BaseController
    {
        [HttpGet]
        public ActionResult Contacts()
        {
            return this.View();
        }

        [HttpGet]
        public ActionResult AboutUs()
        {
            return this.View();
        }
    }
}

Source/Web/HelpMyBook.Web/Views/Shared/_BookMoneyAdder.cshtml
@model HelpMyBook.Web.ViewModels.UserProfile.UserMoneyModel

@using System.Globalization;

<div class="container">
    @if (Model.Money > 0)
    {


        <span class="text-info" style="font-size:20px">You can contribute to this book if you want</span>
        <br />
        using (Html.BeginForm("Contribute", "Books", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.BookId)
            @Html.HiddenFor(m => m.UserId)
            @Html.HiddenFor(m => m.Money)
            <input type="number" id="Contribution" name="Contribution" class="form-control" />
            <input type="submit" id="submit" class="btn btn-success" value="Contribute" />
        }
        <div id="busydiv" style="display:none;"><img src="http://preloaders.net/preloaders/99/Animated%20book-128.gif" alt="loading"/></div>
        <span class="text-info">Currently You have <span class="text-info">@Model.Money.ToString("N", new CultureInfo("en-US"))$</span></span>
    }
    else
    {
        <span class="text-info">Currently You have <span class="text-danger">@Model.Money.ToString("N", new CultureInfo("en-US"))$</span></span>
        <br />
        <span class="text-info" >Add funds if you want to help other authors!</span>
    }
</div>

Source/Web/HelpMyBook.Web/Views/Shared/_FileUpload.cshtml
<div>
    <div>
        <span>Supported formats: txt, doc, docx, pdf</span>
        <input type="file" name="File" id="File" />
        <div id="downloadContainer" style="display:none">
            <label class="control-label" for="downloadable">Is your book downloadable?</label>
            @Html.CheckBox("Downloadable")
        </div>
    </div>
    <br />
    <div>
        <a class="btn btn-primary" onclick="reset($('#file'))">Clear file input</a>
    </div>
</div>

Source/Web/HelpMyBook.Web/Views/Shared/_Layout.cshtml
@using HelpMyBook.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HelpMyBook</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HelpMyBook", "Index", "Home", new { area = string.Empty }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>

                    <li>@Html.ActionLink("Books", "Index", "Books", new { area = string.Empty }, null)</li>

                    <li>@Html.ActionLink("Downloads", "Downloads", "Books", new { area = string.Empty }, null)</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Information<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Contacts", "Contacts", "Information", new { area = string.Empty }, null)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("About us", "AboutUs", "Information", new { area = string.Empty }, null)</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (this.TempData[GlobalConstants.MessageNameError] != null)
        {
            <div class="alert alert-dismissible alert-danger">
                <strong>@TempData[GlobalConstants.MessageNameError]</strong>
            </div>
        }
        @if (this.TempData[GlobalConstants.MessageNameSuccess] != null)
        {
            <div class="alert alert-dismissible alert-success">
                <strong>@TempData[GlobalConstants.MessageNameSuccess]</strong>
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HelpMyBook</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @* @Scripts.Render("~/bundles/unobtr-jq")*@
    @RenderSection("scripts", required: false)
</body>
</html>