Source/Web/HelpMyBook.Web/ViewModels/UserProfile/UserChangeInfoModel.cs
namespace HelpMyBook.Web.ViewModels.UserProfile
{
    using System.ComponentModel.DataAnnotations;

    public class UserChangeInfoModel
    {
        public string Id { get; set; }

        [Url]
        public string AvatarUrl { get; set; }

        [MaxLength(120)]
        public string Name { get; set; }

        [MaxLength(500)]
        [Display(Name="Personal Info")]
        public string PersonalInfo { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/UserProfile/UserInfoModel.cs
namespace HelpMyBook.Web.ViewModels.UserProfile
{
    using HelpMyBook.Data.Models;
    using HelpMyBook.Web.Infrastructure.Mapping;

    public class UserInfoModel : IMapFrom<ApplicationUser>
    {
        public string Id { get; set; }

        public string AvatarUrl { get; set; }

        public string Name { get; set; }

        public int? BookId { get; set; }

        public string Username { get; set; }

        public decimal Money { get; set; }

        public string PersonalInfo { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/UserProfile/UserMoneyModel.cs
namespace HelpMyBook.Web.ViewModels.UserProfile
{
    public class UserMoneyModel
    {
        public string UserId { get; set; }

        public int BookId { get; set; }

        public decimal Money { get; set; }

        public decimal Contribution { get; set; }
    }
}

Source/Web/HelpMyBook.Web/Controllers/BooksController.cs
namespace HelpMyBook.Web.Controllers
{
    using System.IO;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Web.Mvc;
    using HelpMyBook.Common;
    using HelpMyBook.Data.Models;
    using HelpMyBook.Services.Data.Contracts;
    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using reCAPTCHA.MVC;
    using ViewModels.Books;
    using ViewModels.UserProfile;

    public class BooksController : BaseController
    {
        private readonly IUserService users;
        private readonly IBookService books;
        private readonly IFilesService files;
        private readonly IDonationsService donations;

        public BooksController(IUserService users, IBookService books, IFilesService files, IDonationsService donations)
        {
            this.users = users;
            this.books = books;
            this.files = files;
            this.donations = donations;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            var user = this.users.GetUser(this.User.Identity.GetUserId());
            if (user.BookId != null)
            {
                this.TempData.Clear();
                this.TempData[GlobalConstants.MessageNameError] = "You've already created a book!";

                return this.Redirect("/");
            }

            return this.View();
        }

        [HttpPost]
        [Authorize]
        [CaptchaValidator(
        PrivateKey = "6LcfKBkTAAAAAHpUhmpjNks48KyW6g9ITJHFUj2i",
        ErrorMessage = "Invalid input captcha.",
        RequiredMessage = "The captcha field is required.")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookCreateModel model, bool downloadable)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.User.Identity.GetUserId();

            var book = new Book
            {
                Title = model.Title,
                Description = model.Description,
                RequredMoney = model.RequredMoney
            };

            if (model.File != null)
            {
                int idx = model.File.FileName.LastIndexOf('.');
                if (idx == -1)
                {
                    this.ModelState.AddModelError(string.Empty, "File must have an extention!");
                    return this.View();
                }

                var fileName = model.File.FileName.Substring(0, idx);
                var fileExtention = model.File.FileName.Substring(idx + 1);

                if (!Regex.IsMatch(fileExtention, ValidationConstants.FileExtentionRegex))
                {
                    this.ModelState.AddModelError(string.Empty, "File extention not supported!");
                    return this.View();
                }

                using (var memory = new MemoryStream())
                {
                    model.File.InputStream.CopyTo(memory);
                    var content = memory.GetBuffer();

                    book.BookFile = new BookFile
                    {
                        Downloadable = downloadable,
                        Content = content,
                        Name = fileName,
                        FileExtension = fileExtention
                    };
                }
            }

            var user = this.users.GetUser(this.User.Identity.GetUserId());

            var creationResult = this.books.Create(book);

            this.users.BindBookAndUser(user.Id, creationResult.Id);

            this.TempData.Clear();

            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly created a book!";

            return this.RedirectToAction("Details", new { id = creationResult.Id });
        }

        [HttpGet]
        public ActionResult Index()
        {
            var books = this.books.GetBooks().To<BookIndexViewModel>().ToList();
            var hasBook = false;
            if (this.User.Identity.IsAuthenticated)
            {
                var user = this.users.GetUser(this.User.Identity.GetUserId());
                if (user.BookId != null)
                {
                    hasBook = true;
                }
            }

            var model = new BookIndexDataModel()
            {
                Books = books,
                HasBook = hasBook
            };

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Downloads()
        {
            var books = this.books.GetDownloadableBooks().To<BookViewModel>().ToList();

            return this.View(books);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var viewmodel = this.books.GetBookDetails(id).To<BookDetailsViewModel>().FirstOrDefault();

            if (this.User.Identity.IsAuthenticated)
            {
                var user = this.users.GetUser(this.User.Identity.GetUserId());
                if (user.BookId == viewmodel.Id)
                {
                    viewmodel.OwnerLooking = true;
                }

                viewmodel.MoneyPartialModel = new UserMoneyModel()
                {
                    UserId = user.Id,
                    BookId = viewmodel.Id,
                    Money = user.Money
                };
            }

            return this.View(viewmodel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var viewmodel = this.books.GetBookDetails(id).To<BookDetailsViewModel>().FirstOrDefault();

            var user = this.users.GetUser(this.User.Identity.GetUserId());
            if (user.BookId != id)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You are not allowed to edit this book!";
                return this.RedirectToAction("Details", new { id = id });
            }

            return this.View(viewmodel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBookInfo(BookDetailsViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("Edit", model);
            }

            var book = this.books.GetBookDetails(model.Id).FirstOrDefault();

            book.Title = model.Title;
            book.Description = model.Description;

            var creationResult = this.books.Update(book);

            this.TempData.Clear();
            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly created a book!";

            return this.RedirectToAction("Details", new { id = creationResult.Id });
        }

        [HttpGet]
        [Authorize]
        public ActionResult FileUpdate(int bookId)
        {
            var fileId = this.books.GetBookDetails(bookId).FirstOrDefault().BookFileId;
            var model = new BookFileUpdateModel
            {
                BookFileId = fileId,
                BookId = bookId
            };
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult FileUpdate(BookFileUpdateModel model)
        {
            if (model.File != null)
            {
                int idx = model.File.FileName.LastIndexOf('.');
                if (idx == -1)
                {
                    this.ModelState.AddModelError(string.Empty, "File must have an extention!");
                    return this.View("FileUpdate", model);
                }

                var fileName = model.File.FileName.Substring(0, idx);
                var fileExtention = model.File.FileName.Substring(idx + 1);

                if (!Regex.IsMatch(fileExtention, ValidationConstants.FileExtentionRegex))
                {
                    this.ModelState.AddModelError(string.Empty, "File extention not supported!");
                    return this.View("FileUpdate", model);
                }

                using (var memory = new MemoryStream())
                {
                    model.File.InputStream.CopyTo(memory);
                    var content = memory.GetBuffer();
                    var book = this.books.GetBookDetails(model.BookId).FirstOrDefault();
                    if (book.BookFileId == null)
                    {
                        book.BookFile = new BookFile
                        {
                            Downloadable = model.Downloadable,
                            Content = content,
                            Name = fileName,
                            FileExtension = fileExtention
                        };
                    }
                    else
                    {
                        book.BookFile.Downloadable = model.Downloadable;
                        book.BookFile.Content = content;
                        book.BookFile.Name = fileName;
                        book.BookFile.FileExtension = fileExtention;
                    }

                    var result = this.books.Update(book);
                }
            }

            return this.RedirectToAction("Details", new { id = model.BookId });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Contribute(UserMoneyModel model)
        {
            if (model.Money < model.Contribution)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You can't contribute more than you have!";
                return this.RedirectToAction("Details", new { id = model.BookId });
            }

            if (model.Contribution == 0)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You can't contribute 0$!";
                return this.RedirectToAction("Details", new { id = model.BookId });
            }

            var user = this.users.GetUser(model.UserId);

            var donation = new Donation()
            {

Source/Web/HelpMyBook.Web/Controllers/UserProfileController.cs
namespace HelpMyBook.Web.Controllers
{
    using System.Web.Mvc;
    using AutoMapper;
    using Common;
    using Data.Models;
    using HelpMyBook.Services.Data.Contracts;
    using Microsoft.AspNet.Identity;
    using ViewModels.UserProfile;

    [Authorize]
    public class UserProfileController : BaseController
    {
        private IUserService users;

        public UserProfileController(IUserService users)
        {
            this.users = users;
        }

        [HttpGet]
        public ActionResult Info()
        {
            var id = this.User.Identity.GetUserId();

            var config = new MapperConfiguration(cfg => cfg.CreateMap<ApplicationUser, UserInfoModel>());
            var mapper = config.CreateMapper();

            var user = this.users.GetUser(id);
            var viewmodel = mapper.Map<UserInfoModel>(user);
            return this.View(viewmodel);
        }

        [HttpGet]
        public ActionResult ChangeInfo()
        {
            var id = this.User.Identity.GetUserId();

            var config = new MapperConfiguration(cfg => cfg.CreateMap<ApplicationUser, UserChangeInfoModel>());
            var mapper = config.CreateMapper();

            var user = this.users.GetUser(id);
            var viewmodel = mapper.Map<UserChangeInfoModel>(user);
            return this.View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeInfo(UserChangeInfoModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var id = this.User.Identity.GetUserId();
            var user = this.users.GetUser(id);
            if (model.AvatarUrl != null)
            {
                user.AvatarUrl = model.AvatarUrl;
            }

            if (model.PersonalInfo != null)
            {
                user.PersonalInfo = model.PersonalInfo;
            }

            if (model.Name != null)
            {
                user.Name = model.Name;
            }

            this.users.Update(user);

            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly updated your profile!";

            return this.RedirectToAction("Info");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult AddFunds(string id)
        {
            var user = this.users.GetUser(id);

            user.Money += 2000;
            this.users.Update(user);
            this.TempData[GlobalConstants.MessageNameSuccess] = $"You've received 2000$";
            return this.RedirectToAction("Info");
        }
    }
}

Source/Web/HelpMyBook.Web/Views/UserProfile/ChangeInfo.cshtml
@model HelpMyBook.Web.ViewModels.UserProfile.UserChangeInfoModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("ChangeInfo", "UserProfile", new { id = Model.Id }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <h4>Update your account.</h4>
            <hr />
            <div>
                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        </div>
                    </div>
                    <br />
                    <br />
                    <div class="form-group">
                        <label for="avatar" class="col-md-2 control-label">Avatar Url</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.AvatarUrl, new { @class = "form-control", id= "avatar" })
                            @*<input type="url" id="avatar" class="form-control" name="AvatarUrl" />*@
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                            @Html.LabelFor(m => m.PersonalInfo, new { @class = "col-md-2 control-label" })
                    </div>
                    <div class="col-md-10">
                        <textarea name="PersonalInfo" id="PersonalInfo" class="form-control">@Model.PersonalInfo</textarea>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-default" value="Register" />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-3">
        <span>Here you can see if your avatar is displayed</span>
        <hr />
        <img src=@Model.AvatarUrl id="avatarView" style="width:200px;height:200px" alt="If you don't see your picture here the url isn't working!" />
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#avatar').on('input', function () {
                var input = $('#avatar');
                $('#avatarView').attr("src", input.val());
            });
        });
    </script>
}

Source/Web/HelpMyBook.Web/Views/UserProfile/Info.cshtml
@model HelpMyBook.Web.ViewModels.UserProfile.UserInfoModel
@using System.Globalization;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Welcome to your profile!</h1>
<br /><br />
<div class="row">
    <div class="col-md-4">
        <div>Username: <strong>@Model.Username</strong></div>
        <div>Your cash: <strong>@Model.Money.ToString("N", new CultureInfo("en-US"))$</strong></div><br />
        <img src=@Model.AvatarUrl style="width:200px;height:200px" alt="Avatar url" />
    </div>
    <div class="col-md-4 col-md-offset-1">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td class="text-center" colspan="2"><strong>This is your information</strong></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name:</td>
                    @if (Model.Name != null)
                    {
                        <td>@Model.Name</td>
                    }
                    else
                    {
                        <td>Not entered!</td>
                    }
                </tr>
                <tr>
                    <td>Personal Information:</td>
                    @if (Model.PersonalInfo != null)
                    {
                        <td>@Model.PersonalInfo</td>
                    }
                    else
                    {
                        <td>Not entered!</td>
                    }
                </tr>
                <tr>
                    <td>Your book:</td>
                    @if (Model.BookId == null)
                    {
                        <td>
                            @Html.ActionLink("You don't have one. Create!", "Create", "Books", null, new { @class = "btn btn-primary" })
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.ActionLink("Go to your book!", "Details", "Books", new { id = Model.BookId }, new { @class = "btn btn-success" })
                        </td>
                    }
                </tr>
            </tbody>
        </table>
        @Html.ActionLink("Change your information!", "ChangeInfo", "UserProfile", null, new { @class = "btn btn-info" })
        @using (Html.BeginForm("AddFunds", "UserProfile",FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <input type="submit" id="submit" class="btn btn-success" value="Add funds" />
        }
    </div>
    <div class="col-md-4 col-md-offset-1">

    </div>
</div>