Source/Web/HelpMyBook.Web/ViewModels/Books/BookCreateModel.cs
namespace HelpMyBook.Web.ViewModels.Books
{
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using Common;

    public class BookCreateModel
    {
        public HttpPostedFileBase File { get; set; }

        [Required]
        [MaxLength(ValidationConstants.BookTitleMaximum)]
        public string Title { get; set; }

        [Required]
        [MaxLength(ValidationConstants.BookDescriptionMaximum)]
        public string Description { get; set; }

        [Required]
        [Display(Name ="Required money")]
        public decimal RequredMoney { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Books/BookDetailsViewModel.cs
namespace HelpMyBook.Web.ViewModels.Books
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Common;
    using HelpMyBook.Data.Models;
    using HelpMyBook.Web.Infrastructure.Mapping;
    using UserProfile;

    public class BookDetailsViewModel : IMapFrom<Book>
    {
        public int Id { get; set; }

        public bool OwnerLooking { get; set; }

        [Required]
        [MaxLength(ValidationConstants.BookTitleMaximum)]
        public string Title { get; set; }

        [MaxLength(ValidationConstants.BookDescriptionMaximum)]
        public string Description { get; set; }

        public decimal RequredMoney { get; set; }

        public UserMoneyModel MoneyPartialModel { get; set; }

        public virtual BookFile BookFile { get; set; }

        public virtual ICollection<Donation> Donations { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Books/BookFileUpdateModel.cs
namespace HelpMyBook.Web.ViewModels.Books
{
    using System.Web;

    public class BookFileUpdateModel
    {
        public HttpPostedFileBase File { get; set; }

        public int BookId { get; set; }

        public int? BookFileId { get; set; }

        public bool Downloadable { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Books/BookFileViewModel.cs
namespace HelpMyBook.Web.ViewModels.Books
{
    using HelpMyBook.Data.Models;
    using HelpMyBook.Web.Infrastructure.Mapping;

    public class BookFileViewModel : IMapFrom<BookFile>
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Books/BookIndexDataModel.cs
namespace HelpMyBook.Web.ViewModels.Books
{
    using System.Collections.Generic;

    public class BookIndexDataModel
    {
        public IEnumerable<BookIndexViewModel> Books { get; set; }

        public bool HasBook { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Books/BookIndexViewModel.cs
namespace HelpMyBook.Web.ViewModels.Books
{
    using HelpMyBook.Data.Models;
    using HelpMyBook.Web.Infrastructure.Mapping;

    public class BookIndexViewModel : IMapFrom<Book>
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public virtual BookFile BookFile { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Books/BookViewModel.cs
using HelpMyBook.Data.Models;
using HelpMyBook.Web.Infrastructure.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HelpMyBook.Web.ViewModels.Books
{
    public class BookViewModel : IMapFrom<Book>
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public virtual BookFileViewModel BookFile { get; set; }
    }
}

Source/Web/HelpMyBook.Web/ViewModels/Home/BookViewModel.cs
using HelpMyBook.Data.Models;
using HelpMyBook.Web.Infrastructure.Mapping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HelpMyBook.Web.ViewModels.Home
{
    public class BookViewModel : IMapFrom<Book>
    {
        public int Id { get; set; }

        public virtual BookFileViewModel BookFile { get; set; }
    }
}

Source/Web/HelpMyBook.Web/Controllers/BooksController.cs
namespace HelpMyBook.Web.Controllers
{
    using System.IO;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Web.Mvc;
    using HelpMyBook.Common;
    using HelpMyBook.Data.Models;
    using HelpMyBook.Services.Data.Contracts;
    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using reCAPTCHA.MVC;
    using ViewModels.Books;
    using ViewModels.UserProfile;

    public class BooksController : BaseController
    {
        private readonly IUserService users;
        private readonly IBookService books;
        private readonly IFilesService files;
        private readonly IDonationsService donations;

        public BooksController(IUserService users, IBookService books, IFilesService files, IDonationsService donations)
        {
            this.users = users;
            this.books = books;
            this.files = files;
            this.donations = donations;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            var user = this.users.GetUser(this.User.Identity.GetUserId());
            if (user.BookId != null)
            {
                this.TempData.Clear();
                this.TempData[GlobalConstants.MessageNameError] = "You've already created a book!";

                return this.Redirect("/");
            }

            return this.View();
        }

        [HttpPost]
        [Authorize]
        [CaptchaValidator(
        PrivateKey = "6LcfKBkTAAAAAHpUhmpjNks48KyW6g9ITJHFUj2i",
        ErrorMessage = "Invalid input captcha.",
        RequiredMessage = "The captcha field is required.")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookCreateModel model, bool downloadable)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.User.Identity.GetUserId();

            var book = new Book
            {
                Title = model.Title,
                Description = model.Description,
                RequredMoney = model.RequredMoney
            };

            if (model.File != null)
            {
                int idx = model.File.FileName.LastIndexOf('.');
                if (idx == -1)
                {
                    this.ModelState.AddModelError(string.Empty, "File must have an extention!");
                    return this.View();
                }

                var fileName = model.File.FileName.Substring(0, idx);
                var fileExtention = model.File.FileName.Substring(idx + 1);

                if (!Regex.IsMatch(fileExtention, ValidationConstants.FileExtentionRegex))
                {
                    this.ModelState.AddModelError(string.Empty, "File extention not supported!");
                    return this.View();
                }

                using (var memory = new MemoryStream())
                {
                    model.File.InputStream.CopyTo(memory);
                    var content = memory.GetBuffer();

                    book.BookFile = new BookFile
                    {
                        Downloadable = downloadable,
                        Content = content,
                        Name = fileName,
                        FileExtension = fileExtention
                    };
                }
            }

            var user = this.users.GetUser(this.User.Identity.GetUserId());

            var creationResult = this.books.Create(book);

            this.users.BindBookAndUser(user.Id, creationResult.Id);

            this.TempData.Clear();

            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly created a book!";

            return this.RedirectToAction("Details", new { id = creationResult.Id });
        }

        [HttpGet]
        public ActionResult Index()
        {
            var books = this.books.GetBooks().To<BookIndexViewModel>().ToList();
            var hasBook = false;
            if (this.User.Identity.IsAuthenticated)
            {
                var user = this.users.GetUser(this.User.Identity.GetUserId());
                if (user.BookId != null)
                {
                    hasBook = true;
                }
            }

            var model = new BookIndexDataModel()
            {
                Books = books,
                HasBook = hasBook
            };

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Downloads()
        {
            var books = this.books.GetDownloadableBooks().To<BookViewModel>().ToList();

            return this.View(books);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var viewmodel = this.books.GetBookDetails(id).To<BookDetailsViewModel>().FirstOrDefault();

            if (this.User.Identity.IsAuthenticated)
            {
                var user = this.users.GetUser(this.User.Identity.GetUserId());
                if (user.BookId == viewmodel.Id)
                {
                    viewmodel.OwnerLooking = true;
                }

                viewmodel.MoneyPartialModel = new UserMoneyModel()
                {
                    UserId = user.Id,
                    BookId = viewmodel.Id,
                    Money = user.Money
                };
            }

            return this.View(viewmodel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var viewmodel = this.books.GetBookDetails(id).To<BookDetailsViewModel>().FirstOrDefault();

            var user = this.users.GetUser(this.User.Identity.GetUserId());
            if (user.BookId != id)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You are not allowed to edit this book!";
                return this.RedirectToAction("Details", new { id = id });
            }

            return this.View(viewmodel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBookInfo(BookDetailsViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("Edit", model);
            }

            var book = this.books.GetBookDetails(model.Id).FirstOrDefault();

            book.Title = model.Title;
            book.Description = model.Description;

            var creationResult = this.books.Update(book);

            this.TempData.Clear();
            this.TempData[GlobalConstants.MessageNameSuccess] = "You've successfuly created a book!";

            return this.RedirectToAction("Details", new { id = creationResult.Id });
        }

        [HttpGet]
        [Authorize]
        public ActionResult FileUpdate(int bookId)
        {
            var fileId = this.books.GetBookDetails(bookId).FirstOrDefault().BookFileId;
            var model = new BookFileUpdateModel
            {
                BookFileId = fileId,
                BookId = bookId
            };
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult FileUpdate(BookFileUpdateModel model)
        {
            if (model.File != null)
            {
                int idx = model.File.FileName.LastIndexOf('.');
                if (idx == -1)
                {
                    this.ModelState.AddModelError(string.Empty, "File must have an extention!");
                    return this.View("FileUpdate", model);
                }

                var fileName = model.File.FileName.Substring(0, idx);
                var fileExtention = model.File.FileName.Substring(idx + 1);

                if (!Regex.IsMatch(fileExtention, ValidationConstants.FileExtentionRegex))
                {
                    this.ModelState.AddModelError(string.Empty, "File extention not supported!");
                    return this.View("FileUpdate", model);
                }

                using (var memory = new MemoryStream())
                {
                    model.File.InputStream.CopyTo(memory);
                    var content = memory.GetBuffer();
                    var book = this.books.GetBookDetails(model.BookId).FirstOrDefault();
                    if (book.BookFileId == null)
                    {
                        book.BookFile = new BookFile
                        {
                            Downloadable = model.Downloadable,
                            Content = content,
                            Name = fileName,
                            FileExtension = fileExtention
                        };
                    }
                    else
                    {
                        book.BookFile.Downloadable = model.Downloadable;
                        book.BookFile.Content = content;
                        book.BookFile.Name = fileName;
                        book.BookFile.FileExtension = fileExtention;
                    }

                    var result = this.books.Update(book);
                }
            }

            return this.RedirectToAction("Details", new { id = model.BookId });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Contribute(UserMoneyModel model)
        {
            if (model.Money < model.Contribution)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You can't contribute more than you have!";
                return this.RedirectToAction("Details", new { id = model.BookId });
            }

            if (model.Contribution == 0)
            {
                this.TempData[GlobalConstants.MessageNameError] = "You can't contribute 0$!";
                return this.RedirectToAction("Details", new { id = model.BookId });
            }

            var user = this.users.GetUser(model.UserId);

            var donation = new Donation()
            {

Source/Web/HelpMyBook.Web/Controllers/FilesController.cs
namespace HelpMyBook.Web.Controllers
{
    using System.Web.Mvc;
    using HelpMyBook.Services.Data.Contracts;

    public class FilesController : BaseController
    {
        private IFilesService files;

        public FilesController(IFilesService files)
        {
            this.files = files;
        }

        [HttpGet]
        public FileContentResult DownloadBook(int id)
        {
            var bookToDownload = this.files.GetBookFile(id);
            var name = $"{bookToDownload.Name}.{bookToDownload.FileExtension}";
            return this.File(bookToDownload.Content, "application/octet-stream", name);
        }
    }
}

Source/Web/HelpMyBook.Web/Views/Books/Create.cshtml
@model  HelpMyBook.Web.ViewModels.Books.BookCreateModel
@using reCAPTCHA.MVC
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<div>
    @Html.ValidationSummary("", new { @class = "text-danger" })
</div>

@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label for="description" class="col-md-2 control-label">Description</label>
            <div class="col-md-10">
                @if (Model != null && Model.Description != null)
                {
                    <textarea id="description" class="form-control" name="description">@Model.Description</textarea>
                }
                else
                {
                    <textarea id="description" class="form-control" name="description"></textarea>
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.RequredMoney, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.RequredMoney, new { @class = "form-control" })
                <span class= "text-danger">Be careful! Once you create your book you won't be able to change the required money</span>
            </div>
        </div>
        <div>
          <!--Goes here-->
            <span>You can upload your book.</span>
            @Html.Partial("_FileUpload")
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-5">

            </div>
        </div>
        <div>
            @Html.Recaptcha("6LcfKBkTAAAAACaYvskmlUa0dhBJnDXzWpUaiwOr")
        </div>
    </div>
    <div class="col-md-2">
        <input type="submit" value="Create new book" class="btn btn-primary" />
    </div>
}


@section scripts{
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <script>
        $("#File").change(function () {
            if ($('#File').val().length != 0) {
                $("#downloadContainer").show();
            }
            else {
                $("#downloadContainer").hide();
            }
            console.log(
            );
        });
        window.reset = function (e) {
            e.wrap('<form>').closest('form').get(0).reset();
            e.unwrap();
            $("#downloadContainer").hide();

        }
    </script>
}

Source/Web/HelpMyBook.Web/Views/Books/Details.cshtml
@model HelpMyBook.Web.ViewModels.Books.BookDetailsViewModel
@using System.Globalization;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var modelForPartial = Model.MoneyPartialModel;
}

<h1 class="text-center">@Model.Title</h1>
<div class="row">
    <div class="col-md-5">
        <div class="text-justify">
            <span style="font-size:24px">Description of the book:</span>
            <br />
            <span style="font-size:23px"> @Model.Description</span>
        </div>
        <br /><br />
        @if (Model.BookFile != null)
        {
            if (Model.BookFile.Downloadable)
            {
                @Ajax.ActionLink("Download this book", "DownloadBook", "Files", new { id = Model.BookFile.Id }, new AjaxOptions { HttpMethod = "GET" }, new { @class = "btn btn-lg btn-warning" })
            }
            else
            {
                <h3>The owner doesn't want to share his book!</h3>
            }
        }
        else
        {
            <h3>The book isn't uploaded</h3>
        }

        @if (Model.OwnerLooking)
        {
            @Ajax.ActionLink("Edit book", "Edit", new { id = Model.Id }, new AjaxOptions { HttpMethod = "GET" }, new { @class = "btn btn-lg btn-primary" })
        }
    </div>
    <div class="col-md-6 col-md-offset-1">
        <h2>Required amount: <span class="text-info">@Math.Floor(Model.RequredMoney).ToString("N", new CultureInfo("en-US"))$</span></h2>
        <h2>Current amount:  <span class="text-info" id="targetSpan">Required money</span></h2>
        @if (User.Identity.IsAuthenticated)
        {
            @Html.Partial("_BookMoneyAdder", modelForPartial)
        }
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
    $(function () {

        // Proxy created on the fly
        var job = $.connection.bookHub;

        // Declare a function on the job hub so the server can invoke it
        job.client.displayStatus = function () {
            getData();
        };

        // Start the connection
        $.connection.hub.start();
        getData();
    });

    function getData() {
        var $spanForResult = $('#targetSpan');
        $.ajax({
            url: '/BookHub/Result',
            type: 'GET',
            data: {id: @Model.Id},
            datatype: 'json',
            success: function (result) {
              $spanForResult.html(result + "$");
            }
        });
    }
    </script>
}

Source/Web/HelpMyBook.Web/Views/Books/Downloads.cshtml
@model ICollection<HelpMyBook.Web.ViewModels.Books.BookViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model.Count <= 0)
{
    <h1>There are no downloadable books!</h1>
}
else
{
    <div class="row">
        @foreach (var book in Model)
        {
            <div class="col-md-3">
                <h1 class="text-center">@book.Title</h1>
                @Html.ActionLink("Go to the details of the book", "Details", "Books", new { id = book.Id }, new { @class = "btn btn-primary center-block" })
                <br />
                <hr />
                @Ajax.ActionLink("Download", "DownloadBook", "Files", new { id = book.BookFile.Id }, new AjaxOptions { HttpMethod = "GET" }, new { @class = "btn btn-lg btn-warning center-block" })
            </div>
        }
    </div>
}

Source/Web/HelpMyBook.Web/Views/Books/Edit.cshtml
@model HelpMyBook.Web.ViewModels.Books.BookDetailsViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("UpdateBookInfo", "Books", new { id = Model.Id }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <h4>Update your book</h4>
    <hr />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />
            <br />
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    <textarea name="Description" id="Description" class="form-control">@Model.Description</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-success" value="Update your book information" />
                    @Html.ActionLink("Update your book file", "FileUpdate", "Books", new { bookId = Model.Id }, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    </div>

    <div id="posts-wrapper"></div>
}


@section scripts{
<script>
        $("#file").change(function () {
            if ($('#file').val().length != 0) {
                $("#downloadContainer").show();
            }
            else {
                $("#downloadContainer").hide();
            }
            console.log(
            );
        });
        window.reset = function (e) {
            e.wrap('<form>').closest('form').get(0).reset();
            e.unwrap();
            $("#downloadContainer").hide();

        }
</script>

<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
}

Source/Web/HelpMyBook.Web/Views/Books/FileUpdate.cshtml
@model HelpMyBook.Web.ViewModels.Books.BookFileUpdateModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("FileUpdate", "Books", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <span class="text-warning">This will overwrite your old one!</span>
    @Html.Partial("_FileUpload")
    @Html.HiddenFor(m => m.BookId)
    if (Model.BookFileId != null)
    {
        @Html.HiddenFor(m => m.BookFileId)
    }
    <div>
        <input type="submit" value="Update your book" class="btn btn-primary" />
    </div>
}

@section scripts{
    <script>
        $("#File").change(function () {
            if ($('#File').val().length != 0) {
                $("#downloadContainer").show();
            }
            else {
                $("#downloadContainer").hide();
            }
            console.log(
            );
        });
        window.reset = function (e) {
            e.wrap('<form>').closest('form').get(0).reset();
            e.unwrap();
            $("#downloadContainer").hide();

        }
    </script>
}

Source/Web/HelpMyBook.Web/Views/Books/Index.cshtml
@model HelpMyBook.Web.ViewModels.Books.BookIndexDataModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (User.Identity.IsAuthenticated && !Model.HasBook)
{
    <br />
    @Html.ActionLink("Create your book!", "Create", "Books", null, new { @class = "btn btn-primary btn-lg" })
}
@if (Model.Books.Count() <= 0)
{
    <h1>There are no books!</h1>
}
else
{
    <div class="row">
        @foreach (var book in Model.Books)
        {
            <div class="col-md-5">
                <h1 class="text-center">@book.Title</h1>
                <div>
                    <span>
                        @book.Description
                    </span>
                </div>
                <div>
                    <span>
                        <strong>Downloadable?</strong>
                    </span>
                    @if (book.BookFile != null && book.BookFile.Downloadable)
                    {
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-thumbs-down"></span>
                    }
                </div>
                @Html.ActionLink("Go to the details of the book", "Details", "Books", new { id = book.Id }, new { @class = "btn btn-primary center-block" })
                <br />
                <hr />
            </div>
        }
    </div>
}